function f = asym_func_neff(x,d,k,n1,n2,n3,mode_num)
    f = 2*d*sqrt(k*k*(n2*n2-x*x))...
        - 2*atan(sqrt(x*x-n1*n1)/sqrt(n2*n2-x*x))...
        - 2*atan(sqrt(x*x-n3*n3)/sqrt(n2*n2-x*x))-mode_num*2*pi;